### ISSUE TITLE
[FE] Delete account

### ISSUE THREAD

**Issue by arecvlohe** [nativesintech/native-owned-businesses#15]
## Background

User may want to delete their account and consequently all of their businesses as well.

## Acceptance Criteria

- [ ] Suggest design
- [ ] A delete button that allows the user to delete their account
- [ ] A confirmation modal that pops up after the user clicked the delete button
- [ ] Redirect to list view

## Tasks

- [ ] Determine using delete vs deactivate or public vs private mechanims
