### ISSUE TITLE
[FE] Preview business

### ISSUE THREAD

**Issue by arecvlohe** [nativesintech/native-owned-businesses#16]
## Background

Before publishing the admin can see the the listing of their business in a sandboxed environment like preview

## Acceptance Criteria

- [x]  Suggest UI/UX
  - [x] Button dropdown
- [x] Clicking the preview button shows the admin what the listing would look like

## Tasks

- [x] Preview vs Public in the database
