### ISSUE TITLE
[FE] Share business view

### ISSUE THREAD

**Issue by arecvlohe** [nativesintech/native-owned-businesses#22]
## Background

Provide mechanism for a user to be able to share their listing on the site for a single isolated listing

## Acceptance Criteria

- [x] Isolated page for each business to be shared

## Tasks

- [ ] Suggest design
- [x] Create new view
- [x] Create new route that takes query param of the uuid of the business
